---
- name: Установка NGINX в Docker на веб-серверах
  hosts: web_servers
  become: true
  tasks:
    - name: Убедитесь, что процессы apt не запущены
      shell: |
        ps aux | grep '[a]pt' | awk '{print $2}' | xargs -r kill -9
      ignore_errors: true

    - name: Удалить файл блокировки /var/lib/apt/lists/lock, если он существует
      file:
        path: /var/lib/apt/lists/lock
        state: absent

    - name: Удалить файл блокировки /var/cache/apt/archives/lock, если он существует
      file:
        path: /var/cache/apt/archives/lock
        state: absent

    - name: Удалить файл блокировки /var/lib/dpkg/lock-frontend, если он существует
      file:
        path: /var/lib/dpkg/lock-frontend
        state: absent

    - name: Удалить файл блокировки /var/lib/dpkg/lock, если он существует
      file:
        path: /var/lib/dpkg/lock
        state: absent

    - name: Перезагрузка dpkg для восстановления базы данных
      command: dpkg --configure -a

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Проверка, что pip установлен
      apt:
        name: python3-pip
        state: present

    - name: Установка библиотеки docker для Python
      pip:
        name: docker
        state: present
        container_default_behavior: no_defaults  # Явное значение для параметра
     
    # Обновление кеша apt
    - name: Проверка, что Docker установлен
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Запуск и включение службы Docker
    - name: Запустить службу Docker
      service:
        name: docker
        state: started
        enabled: true

    # Загрузка образа Nginx из Docker Hub
    - name: Загрузить образ Nginx
      docker_image:
        name: nginx
        source: pull

    # Создание локальной директории для статических файлов
    - name: Создать директорию для статических файлов
      file:
        path: /var/www/html/
        state: directory
        mode: '0755'

    # Копирование статических файлов сайта на сервер
    - name: Копировать файлы статического сайта на сервер
      copy:
        src: static/           # Исходная директория с файлами на локальной машине
        dest: /var/www/html/    # Целевая директория на сервере
        mode: '0755'

    # Запуск контейнера Nginx с пробросом порта и монтированием статических файлов
    - name: Запустить контейнер Nginx с монтированием статических файлов
      docker_container:
        name: nginx
        image: nginx
        state: started
        ports:
          - "80:80"                 # Проброс порта 80 с хоста в контейнер
        volumes:
          - /var/www/html/:/usr/share/nginx/html:ro  # Монтирование директории со статическими файлами в контейнер
        restart_policy: always       # Политика перезапуска контейнера