---
- name: Setup Ansible on server
  hosts: bastion
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes

    # Копирование SSH-ключей с использованием модуля synchronize
    - name: Copy SSH private key
      ansible.builtin.synchronize:
        src: /home/user/.ssh/id_ed25519  # Путь к ключу на локальной машине
        dest: /home/ubuntu/.ssh/  # Путь на удаленной машине
      delegate_to: localhost  # Выполняет действие на локальной машине
      become: false  # Нет необходимости поднимать привилегии на локальной машине

    - name: Copy SSH public key
      ansible.builtin.synchronize:
        src: /home/user/.ssh/id_ed25519.pub
        dest: /home/ubuntu/.ssh/
      delegate_to: localhost
      become: false

    - name: Set correct ownership for SSH keys
      ansible.builtin.file:
        path: /home/ubuntu/.ssh/id_ed25519  # Путь к приватному ключу
        owner: ubuntu
        group: ubuntu
        mode: '0600'  # Доступ только для владельца (рекомендуется для приватных ключей)

    - name: Set correct ownership for SSH public key
      ansible.builtin.file:
        path: /home/ubuntu/.ssh/id_ed25519.pub  # Путь к публичному ключу
        owner: ubuntu
        group: ubuntu
        mode: '0644'  # Доступ на чтение для всех (рекомендуется для публичных ключей)

    # Копирование директории web_server с рекурсией
    - name: Copy directory web_server
      ansible.builtin.synchronize:
        src: /home/user/diplom/web_server  # Локальный путь
        dest: /home/ubuntu/  # Путь на удаленной стороне
        recursive: true
        delete: no  # Сохраняет файлы, которых нет в локальной директории
      delegate_to: localhost
      become: false