---
- name: Setup NGINX on web servers
  hosts: web_servers
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy static website files
      copy:
        src: static/
        dest: /var/www/html/
        mode: '0755'

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: true